/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test_2;

import Help.Chk;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baphuoc
 */
public class QL_SinhVien extends javax.swing.JFrame {

    ArrayList<SinhVien> listSV = new ArrayList<>();
    DefaultTableModel model;

    /**
     * Creates new form QL_SinhVien
     */
    public QL_SinhVien() {
        initComponents();
        setLocationRelativeTo(null);

        listSV.add(new SinhVien("Nguyễn Bá Phước", "Đức", 65));
        listSV.add(new SinhVien("Nguyễn A", "Nhật", 55));
        listSV.add(new SinhVien("Nguyễn B", "Hàn Quốc", 44));
        listSV.add(new SinhVien("Nguyễn C", "Anh", 90));
        model = (DefaultTableModel) tblSinhVien.getModel();
        filltotable();

        txtHoTen.setText(listSV.get(0).getHoTen());
        txtCanNang.setText(String.valueOf(listSV.get(0).getCannang()));
        cboNgoaiNgu.setSelectedItem(listSV.get(0).getNgoaiNgu());
        lblText.setText("1/"+listSV.size());
        tblSinhVien.setRowSelectionInterval(0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        cboNgoaiNgu = new javax.swing.JComboBox<>();
        txtCanNang = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ Tên:");

        jLabel2.setText("Cân Nặng:");

        jLabel3.setText("Ngoại ngữ:");

        cboNgoaiNgu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anh", "Nhật", "Hàn Quốc", "Trung Quốc", "Đức" }));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnclose.setText("<<");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        lblText.setText("1/4");

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ Tên", "Câ Nặng", "Ngoại Ngữ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(txtHoTen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboNgoaiNgu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboNgoaiNgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnclose)
                    .addComponent(btnNext)
                    .addComponent(btnLast)
                    .addComponent(lblText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        save();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        int index = tblSinhVien.getSelectedRow();
        txtHoTen.setText(listSV.get(index).getHoTen());
        txtCanNang.setText(String.valueOf(listSV.get(index).getCannang()));
        cboNgoaiNgu.setSelectedItem(listSV.get(index).getNgoaiNgu());
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        txtHoTen.setText(listSV.get(0).getHoTen());
        txtCanNang.setText(String.valueOf(listSV.get(0).getCannang()));
        cboNgoaiNgu.setSelectedItem(listSV.get(0).getNgoaiNgu());
        lblText.setText("1/"+listSV.size());
        tblSinhVien.setRowSelectionInterval(0,0);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        int index = listSV.size() - 1;
        txtHoTen.setText(listSV.get(index).getHoTen());
        txtCanNang.setText(String.valueOf(listSV.get(index).getCannang()));
        cboNgoaiNgu.setSelectedItem(listSV.get(index).getNgoaiNgu());
        lblText.setText(listSV.size()+"/"+listSV.size());
        tblSinhVien.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        int index = 0;
        for (int i = 0; i < listSV.size(); i++) {
            if(listSV.get(i).getHoTen().equalsIgnoreCase(txtHoTen.getText())){
                index = i-1;
            }
        }
        txtHoTen.setText(listSV.get(index).getHoTen());
        txtCanNang.setText(String.valueOf(listSV.get(index).getCannang()));
        cboNgoaiNgu.setSelectedItem(listSV.get(index).getNgoaiNgu());
        lblText.setText((index+1)+"/"+listSV.size());
        tblSinhVien.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        int index = 0;
        for (int i = 0; i < listSV.size(); i++) {
            if(listSV.get(i).getHoTen().equalsIgnoreCase(txtHoTen.getText())){
                index = i+1;
            }
        }
        txtHoTen.setText(listSV.get(index).getHoTen());
        txtCanNang.setText(String.valueOf(listSV.get(index).getCannang()));
        cboNgoaiNgu.setSelectedItem(listSV.get(index).getNgoaiNgu());
        lblText.setText((index+1)+"/"+listSV.size());
        tblSinhVien.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_SinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnclose;
    private javax.swing.JComboBox<String> cboNgoaiNgu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblText;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtCanNang;
    private javax.swing.JTextField txtHoTen;
    // End of variables declaration//GEN-END:variables

    private void filltotable() {
        model.setRowCount(0);
        for (SinhVien s : listSV) {
            model.addRow(new Object[]{s.getHoTen(), s.getCannang(), s.getNgoaiNgu()});
        }
    }

    public void clear() {
        txtHoTen.setText("");
        txtCanNang.setText("");
        cboNgoaiNgu.setSelectedIndex(0);
        lblText.setText("");
    }

    public void save() {
        //Họ Tên
        String hoten = txtHoTen.getText();
        try {
            if (Chk.chknull(txtHoTen, "Vui lòng không để trống họ tên!!!")) {
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
            return;
        }

        //Cân nặng
        double cannang;
        try {
            if (Chk.chknull(txtCanNang, "Vui lòng không để trống cân nặng!!!")) {
                return;
            }
            if (Chk.chkCanNang(txtCanNang, "Cân nặng không hợp lệ!!!")) {
                return;
            }
            cannang = Double.parseDouble(txtCanNang.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cân nặng phải là số!!!");
            return;
        }

        //Ngoại ngữ
        String ngoaingu = (String) cboNgoaiNgu.getSelectedItem();
        listSV.add(new SinhVien(hoten, ngoaingu, cannang));
        filltotable();
        clear();
    }

    public void delete() {
        for (int i = 0; i < listSV.size(); i++) {
            if (listSV.get(i).getHoTen().equals(txtHoTen.getText())) {
                int hoi = JOptionPane.showConfirmDialog(this, "Xóa nhân viên " + listSV.get(i).getHoTen() + " ?");
                if (hoi == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this, "Bạn đã xóa nhân viên: " + listSV.get(i).getHoTen());
                }
                clear();
                listSV.remove(i);
            }
        }
        filltotable();
    }
}
